name: k6 CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: grafana/k6-ci/.github/workflows/all.yml@41aaf8e365b56fd120b0396beae2eba3969babab # v0.5.1
    with:
      k6-ci-ref: 41aaf8e365b56fd120b0396beae2eba3969babab # v0.5.1

  docs-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Resolve Go versions
        id: go-versions
        uses: grafana/k6-ci/.github/actions/go-versions@41aaf8e365b56fd120b0396beae2eba3969babab # v0.5.1
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ steps.go-versions.outputs.current }}
          cache: false
          check-latest: true
      - name: Verify dependencies
        working-directory: docs
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum
          go mod verify
      - name: Lint
        run: make lint-docs
      - name: Test
        working-directory: docs
        run: go test -race -count=1 ./...
